import Head from 'next/head';

import Layout from "../../src/Components/layout/layout";
import Shakhrisabz from "../../src/Components/Shakhrisabz/Shakhrisabz";

;


export default function Stricture() {
	return (
		<>
			<Head>
				<title>Stricture</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>			        
			<Shakhrisabz/>
			</Layout>
		</>
	);

	
}
