const add__info = {
   landslides: "Ko'chkilar",
   funnels: "Tutun  trubinas",
   collapses: "Qulab tushadi",
   avalanche: "Qor ko'chkisi",
   about:{
      about__text1: "Fotosuratlar: Tarixiy, kundalik faoliyat va xalqaro hamkorlik (uchrashuvlar) Tarix",
      about__text2:"O‘zbekiston Respublikasi Xavfli geologik jarayonlar monitoringi davlat xizmati (keyingi o‘rinlarda Davlat monitoring xizmati deb yuritiladi) aholi va xo‘jalik obyektlarini xavfli ekzogen geologik jarayonlar rivojlanishidan aniqlash va o‘z vaqtida ogohlantirish bo‘yicha faoliyatni amalga oshiruvchi yagona tashkilotdir.",
      about__text3:"Xizmat tarixi 1958-yilda Bo‘stonliq ko‘chki partiyasi tashkil etilganidan va 1994-yilda respublikamizning tog‘oldi va tog‘li hududlarida alohida hududiy kuzatuv stansiyalariga ega bo‘lgan Davlat kuzatuv xizmatiga qadar davom etadi. Kuzatuv xizmati mutaxassislari avtomobil yoʻllari, temir yoʻllar, infratuzilma obʼyektlarida eng kichik deformatsiyalar va koʻchki jarayonlarining rivojlanishini aniqlash maqsadida zamonaviy topografik-geodeziya oʻlchash asboblari hamda Yerni masofadan zondlash materiallaridan foydalangan holda muhandislik-geologik tadqiqotlar olib boradilar. ob'ektlar, tog'-kon inshootlari va aholi punktlari yaqinida.",
      about__text4: "Hozirda",
      about__text5:"Bugungi kunda Davlat kuzatuv xizmati markazlashgan boshqaruv apparatiga, Toshkent shahrida joylashgan ixtisoslashtirilgan boshqarmalarga va “O‘zbekiston Respublikasining xavfli geologik jarayonlarni monitoring qilish davlat xizmati to‘g‘risida”gi nizomga (keyingi o‘rinlarda deb yuritiladi) muvofiq faoliyat yurituvchi 7 ta hududiy kuzatuv stansiyalariga ega. Nizomga muvofiq) Oʻzbekiston Respublikasining Toshkent, Ohangaron, Namangan, Fargʻona, Andijon, Samarqand, Navoiy, Jizzax, Qashqadaryo va Surxondaryo viloyatlarining togʻoldi va togʻli hududlarida.",
      about__text6:"Davlat kuzatuv xizmatining ustuvor vazifasi shu maqsadda o‘z faoliyatini davlat va xo‘jalik boshqaruvi organlari, mahalliy davlat hokimiyati organlari va boshqa tashkilotlar bilan hamkorlikda amalga oshirishdan iborat.",
      about__text7:"Asosan, faoliyat ham me'yoriy hujjatlar, ham ichki qoidalar, ham me'yoriy hujjatlar bilan tartibga solinadi. Har bir hududiy kuzatuv stansiyasi hududiy kuzatuv stantsiyasining boshlig'i lavozimida monitoring mintaqasi va boshlig'iga muvofiq o'z bazasiga ega. Kuzatuv stansiyalarida yetakchi mutaxassislar, gidrogeologlar, texnik xodimlar va yuqori malakali haydovchilarga ega avtotransportlar parki ishlaydi. Xavfli ekzogen geologik jarayonlarning namoyon boʻlishiga tezkorlik bilan munosabatda boʻlish uchun hududiy kuzatuv stansiyalari xodimlari zarur avtotransport vositalari hamda kuzatuv ishlarini oʻlchash va oʻtkazish uchun zamonaviy asboblar bilan taʼminlangan.",
      about__text8:"Davlat kuzatuv xizmatida ishlarning to‘liq ishlashi va tezkor tashkil etilishi uchun geodeziya ishlari, geologiya-qidiruv, kartografiya va GIS texnologiyalari bo‘yicha ixtisoslashtirilgan bo‘limlar, amalga oshirilayotgan ishlar sifati va axborot mazmunini oshirish uchun hududiy kuzatuv stansiyalarining mutaxassislari hamrohlik qilmoqda. . Shuningdek, muhandislik-geologik qidiruv ishlarining ilmiy qismi Davlat kuzatuv xizmati faoliyatining ajralmas qismi bo‘lib, xodimlarning bilimini oshirish va amalga oshirilayotgan ishlar to‘g‘risida aholining xabardorligini oshirish maqsadida muntazam ravishda seminarlar, brifinglar va konferensiyalar o‘tkazib borishini alohida ta’kidlash lozim. va xizmat faoliyati. Tadqiqot ob'ektlari",
      about__text9:"Davlat kuzatuv xizmatining ilmiy-tadqiqot obʼyektlari keng tarmoqqa ega boʻlib, asosiy yoʻnalish koʻchki xavfini baholash boʻyicha muhandislik-geologik tadqiqotlar hisoblanadi.",
      about__text10:"xavfli ekzogen geologik jarayonlarni monitoring qilish, gidrotexnika inshootlari, tog'-kon inshootlari, avtomobil va temir yo'llar, elektr uzatish liniyalari, magistral quvurlar, ijtimoiy tarmoqlarning xavfsiz va uzluksiz ishlashini, texnik xizmat ko'rsatishini, rejalashtirish va qurishni ta'minlash bo'yicha tavsiyalar va chora-tadbirlar rejasini ishlab chiqish va tegishli choralarni ko'rish; va Oʻzbekiston Respublikasining togʻ oldi va togʻli hududlarida joylashgan boshqa infratuzilma obʼyektlari.",
      about__text11:"Davlat nazorati xizmatida qator zamonaviy texnik va kasbiy jihatlarning mavjudligi o‘z sohasi mutaxassislariga yuklatilgan har bir vazifaga individual yondashuvni tanlash imkonini beradi. Xususan, muhandislik geologiyasi, raqamlashtirish va GIS texnologiyalari sohasida qo‘yilgan vazifalarni eng qisqa muddatlarda bajarish imkonini beruvchi kompleks ishlar amalga oshirilayotganini alohida ta’kidlash lozim.",
      about__text12:"Rivojlanish strategiyasi",
      about__text13:"Ayni paytda Davlat kuzatuv xizmati tomonidan moddiy-texnik bazani jadal modernizatsiya qilish ishlari olib borilmoqda va xodimlarning xalqaro tillar, ixtisoslashgan yo‘nalishlar bo‘yicha bilim saviyasini oshirish, asosan shu sohadagi shu kabi profildagi yetakchi tashkilotlar tajribasini o‘rganish orqali bir qator chora-tadbirlar amalga oshirilmoqda. dunyoning boshqa mamlakatlari. Xizmatning asosiy maqsadi va pozitsiyasi - xizmat ko'rsatish jarayonida minimal inson omili ta'siri bilan monitoring, prognozlash va axborot uzatish jarayonlarini to'liq optimallashtirish va avtomatlashtirishga erishish. Bu amalga oshirilayotgan ishlar samaradorligini sezilarli darajada oshiradi va respublika hududida xavfli ekzogen geologik jarayonlarning namoyon boʻlishidan ham ijtimoiy, ham iqtisodiy zararni minimallashtiradi.",
      about__text14:"Bu borada Davlat nazorati xizmati xalqaro hamkorlik tashkilotlari, kompaniyalar va boshqa ilmiy muassasalar bilan hamkorlikda ilmiy-tadqiqot va amaliy ishlarni faol olib bormoqda.",
}

}
export default add__info