import Head from 'next/head';

import Layout from "../src/Components/layout/layout";
import Charters from "../src/Components/charter/charter";
;


export default function Charter() {
	return (
		<>
			<Head>
				<title>Charter</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
		<Charters/>
			</Layout>
		</>
	);

}
