import Head from 'next/head';

import Layout from "../src/Components/layout/layout";
import Contact from "../src/Components/contact/contact";
;


export default function Home() {
	return (
		<>
			<Head>
				<title>Contact</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Layout>
			<Contact/>
			</Layout>
		</>
	);

}
