import Head from 'next/head';

import Layout from "../src/Components/layout/layout";
import Fight from "../src/Components/Fight/fight";
;


export default function LegalStatus() {
	return (
		<>
			<Head>
				<title>Youth policy</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
		<Fight/>
			</Layout>
		</>
	);

}
