import Head from 'next/head';

import Layout from "../src/Components/layout/layout";
import Geological from "../src/Components/Geological/Geological";
;


export default function LegalStatus() {
	return (
		<>
			<Head>
				<title>Geological</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
		<Geological/>
			</Layout>
		</>
	);

}
