import Head from 'next/head';

import Layout from "../src/Components/layout/layout";
import Information from "../src/Components/Information/information";
;


export default function LegalStatus() {
	return (
		<>
			<Head>
				<title>Information</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
		<Information/>
			</Layout>
		</>
	);

}
