import Head from 'next/head';

import Layout from "../src/Components/layout/layout";
import International from "../src/Components/International/international";
;


export default function LegalStatus() {
	return (
		<>
			<Head>
				<title>International</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
		<International/>
			</Layout>
		</>
	);

}
